### ISSUE TITLE
几个问题：一个是多边不同颜色或者样式的设置，一个是设置设置奇偶隔数设置，一个是多边框嵌套

### ISSUE THREAD

**Issue by yang123guo** [huanghuiquan/1px#1]
作者您好，感谢您的插件，我目前提几个遇到的问题。
1、一个是多边不同颜色或者样式的设置 ：比如一个div框，上面想设置蓝色，下面想设置成红色，set-border-color(red)会使后面的颜色覆盖前面的，意思是同一属性的覆盖性，不能定制。
2、我的业务是多个div框float：left，那么如果用css来控制的话可以有nth-child()来控制最右边的没有右边框，但是你这写到标签里面比较麻烦了，还得加入js控制。
3、还是因为只能在标签中写类名，如果多个带边框的div嵌套的话，set-border-color()因为不能具体精确到哪一个标签，没法定制，导致样式都是统一的。

**Comment by huanghuiquan** [comment]
1. set-border-color只是一个简单封装了一下的函数，具体如下：
```css
// 设置边框颜色
set-border-color(color)
    border-color: color

    &::after
        border-color: color
```
所以你完全可以这样是写来实现不同边框实现不同的颜色：
```css
.div-with-border
    border-color-left: red
    border-color-right: white

    &::after
        border-color: red
        border-color-right: white
```

2. 这个的原理也是一样：
```css
.div-with-border:nth-child(n)
    border-color-left: red
    border-color-right: white

    &::after
        border-color: red
        border-color-right: white
```

3. set-border-color()是可以定制到某个标签的,例子如下
```
.special-div-with-border
    set-border-color(red)
```
